---
title: "Pilot_Study_Analysis"
author: "Shan He"
date: "4/4/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(lmtest)
library(sandwich)
library(multiwayvcov)
library(data.table)
library(stargazer)
library(dplyr)
```

```{r}
d <- read.csv('Pricing Research Final Collection(normalized).csv')
d <- data.table(d)

#delete useless columns
d[, c("Collector.ID", "Start.Date", "End.Date" ) := NULL]

head(d, 20)
```

#create variables for blocks (food item), and factors (font family, typography) 
```{r}
#item number (block)
d[, item_number := substr(Item, 5, 5)]

#font family (factor)
d[, font_family := case_when(
                      substr(Item, 7, 8) == 'Ro' ~ "Roboto",
                      substr(Item, 7, 8) == 'Jo' ~ "Josefin",
                      substr(Item, 7, 8) == 'PT' ~ "PT")]
d[, typography := case_when(
                      (font_family == 'Roboto' & substr(Item, 13, 13) == 'S') ~ 'Serif',
                      (font_family == 'Roboto' & substr(Item, 13, 13) != 'S') ~ 'Sans',
                      (font_family == 'Josefin' & substr(Item, 14, 18) != 'Slab') ~ 'Serif',
                      (font_family == 'Josefin' & substr(Item, 14, 18) != 'Sans') ~ 'Sans',
                      (font_family == 'PT' & substr(Item, 9, 13) != 'Serif') ~ 'Serif',
                      (font_family == 'PT' & substr(Item, 9, 13) != 'Sans') ~ 'Sans')]

#treatment variable Serif
d[, serif := case_when( typography == 'Serif' ~ 1,
                        typography == 'Sans' ~ 0)]

#exclude unqualified answers
#1. exclude people who googled
d <- d[substr(Google, 1, 2) == 'No',]

#2. exclude people who used phone or tablet
d <- d[Device.Type != 'iOS Phone / Tablet',]


#create dummy variable for gender
unique(d$Gender.1)
d[, male := case_when( Gender.1 == 'Male' ~ 1,
                        Gender.1 == 'Female' ~ 0)]

#list item 1 price for standardization
item1 <- d[item_number == "1", .(Respondent.ID, item1_price = Item_Price, item1_font = paste(font_family, typography, sep = "_"))]
head(item1)

#check for any zero item1
item1[item1_price == 0]

#exclude these two people
item1 <- item1[item1_price != 0]

#join item 1 price for standardization
setkey(d, Respondent.ID)
setkey(item1, Respondent.ID)
df <- d[item1, nomatch = 0]

#create standardized price
df[, price_index := Item_Price / item1_price]

head(df)

ATE_model_Price_Index <- lm(price_index ~ serif * factor(font_family) + factor(item_number) + factor(Food_Preference) + Income_Question + Age_Question + male + factor(Region) + factor(item1_font), data = df)

ATE_model_Price_Index$cluster1.vcov <- cluster.vcov(ATE_model_Price_Index, ~ Respondent.ID)

stargazer(
          ATE_model_Price_Index, 
          type = "text", 
          se=list(sqrt(diag(ATE_model_Price_Index$cluster1.vcov)))
          )

```

#Price
```{r}
hist(d[, Item_Price], breaks = 30, main = 'Histogram of Price', xlab = 'Price')

hist(df[, price_index], breaks = 10, main = 'Histogram of Price Index', xlab = 'Price Index')
```

#exlude unqualified answers
```{r}
#1. exclude people who googled
d <- d[substr(Google, 1, 2) == 'No',]

#2. exclude people who used phone or tablet
d <- d[Device.Type != 'iOS Phone / Tablet',]

#3. exclude people $0 answers
d <- d[Item_Price != 0,]

summary(d)
```

#Age Group
```{r}
hist(d[, Age_Question], breaks = 20, main = 'Histogram of Age', xlab = 'Age', xlim = range(0, 100))
```

#Income Level
```{r}
hist(d[, Income_Question], breaks = 30, main = 'Histogram of Income', xlab = 'Income')
```

#covariate balance check

```{r}
summary(d$Age_Question)

# age_check <- lm(Age_Question ~ serif + factor(font_family) + factor(item_number), data = d)
# income_check <- lm(Income_Question ~ serif + factor(font_family) + factor(item_number), data = d)

#gender_check <- lm(male ~ serif + factor(font_family) + factor(item_number), data = d)
#region_check <- lm(Region ~ serif + factor(font_family) + factor(item_number), data = d)

#stargazer(age_check, 
#          income_check, 
#          gender_check, 
#          type = "text")

model_simple <- lm(serif ~ 1, data = d)
model_covariates <- lm(serif ~ 1 + Age_Question + Income_Question + male + factor(Region) + factor(Food_Preference), data = d)

anova(model_simple, model_covariates)
```

#treatment effect
```{r}
# ATE_model_short <- lm(Item_Price ~ serif + factor(font_family) + factor(item_number) + factor(Food_Preference)+ Income_Question + Age_Question + male, data = d)
# ATE_model_short$cluster1.vcov <- cluster.vcov(ATE_model_short, ~ Respondent.ID)

#short model
ATE_model_0 <- lm(Item_Price ~ serif * factor(font_family), data = d)


ATE_model_short <- lm(Item_Price ~ serif * factor(font_family) + factor(Respondent.ID), data = d)
ATE_model_short$cluster1.vcov <- cluster.vcov(ATE_model_short, ~ Respondent.ID)

#long model, ignoring people with empty region
ATE_model_long <- lm(Item_Price ~ serif * factor(font_family) + factor(item_number) + factor(Food_Preference) + Income_Question + Age_Question + male + factor(Region), data = d[Region != ''])
ATE_model_long$cluster1.vcov <- cluster.vcov(ATE_model_long, ~ Respondent.ID)

# 
# stargazer(
#           ATE_model_short,
#           ATE_model_long,
#           type = "text"
#           )

stargazer(ATE_model_0, ATE_model_short, type = "text", omit = "Respondent.ID")


stargazer(ATE_model_short, type = "text", se=list(sqrt(diag(ATE_model_short$cluster1.vcov))))

stargazer(ATE_model_short,
          ATE_model_long, 
          type = "text", 
          omit = "Respondent.ID",
          se=c(list(sqrt(diag(ATE_model_short$cluster1.vcov))), list(sqrt(diag(ATE_model_long$cluster1.vcov)))), 
          add.lines = list(c("Fixed effects?", "No", "Yes"))
          )
```


#check to see within-block treatment effect
```{r}
ATE_model_short_PT <- lm(Item_Price ~ serif + factor(item_number) + Income_Question + Age_Question + male, data = d[font_family == 'PT'])

stargazer(ATE_model_short_PT, type = "text", se=list(sqrt(diag(vcovHC(ATE_model_short_PT)))))
```


```{r}
ATE_model_short_Item1 <- lm(Item_Price ~ serif + factor(font_family) + Income_Question + Age_Question + male, data = d[item_number == '1'])

stargazer(ATE_model_short_Item1, type = "text", se=list(sqrt(diag(vcovHC(ATE_model_short_Item1)))))
```

#power analysis

```{r}
library(pwr)
pwr.t.test(d = )
```
